### ISSUE TITLE
Failed to locate @site-title-font-letter-spacing

### ISSUE THREAD

**Issue by robertgaal** [Squarespace/base-template#1]
When using this base template out of the box, the LESS compiler fails:

Line            Statement
-------------------------
base.less:1     .site-title {
base.less:1         a {
base.less:7161          padding-left: @site-title-font-letter-spacing

ExecuteError VAR_UNDEFINED: Failed to locate a definition for the variable @site-title-font-letter-spacing in current scope

**Comment by foleyatwork** [comment]
Hey thanks for the heads up. I should be at a computer sometime in the next 3 hours, I'll fix this.

**Comment by alexpapworth** [comment]
Hey dude, did you fix this? I'm having a similar issue with @heading3-font-letter-spacing

**Comment by esquareda** [comment]
I don't see that Foley has made a change to that variable and I'm not able to recreate the problem.
